development:
  adapter: postgresql
  encoding: unicode
  database: datester_development
  host: localhost
  pool: 5
  username: postgres
  password: mateo525




production:
  adapter: postgresql
  encoding: unicode
  database: datester_development  #name is name of app _development
  pool: 5
  host: localhost
  username: postgres
  password: mateo525
